baseURL = "https://mallozup.github.io/"
languageCode = "en-us"
title = "(def Think humble, think free) --> "
theme = "coder"

paginate = 20
canonifyurls = true

[params]
    author = "Dario Maiocchi"
    info = "Free Software, remote developer with strong linux Culture | Painter"
    description = "Dario Maiocchi's personal website"
    keywords = "foss, lisp, linux, clojure and other stuff around software"
    footercontent = "free software, free thoughts"

    rtl = false

    math = true
    custom_css = ["css/custom.css"]


# Social links
[[params.social]]
    name = "Github"
    icon = "fab fa-github fa-2x"
    weight = 1
    url = "https://github.com/MalloZup"
[[params.social]]
    name = "Twitter"
    icon = "fab fa-twitter fa-2x"
    weight = 3
    url = "https://twitter.com/DarioMaiocchi"

[[params.social]]
    name = "Instagram Paintings"
    icon = "fab fa-instagram fa-2x"
    weight = 2
    url = "https://www.instagram.com/dario_maiocchi_art/"




# Menu links
[[menu.main]]
    name = "Blog"
    weight = 1
    url  = "/posts/"
