baseURL = "https://mallozup.github.io/"
languageCode = "en-us"
title = "#MalloZup: coding for better Opensource and Linux"
theme = "ananke"

MetaDataFormat = "yaml"
DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 3 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  favicon = ""
  description = "Blog idea contribution about opensource coding on Linux world."
  facebook = ""
  twitter = ""
  instagram = ""
  youtube = ""
  github = "https://github.com/MalloZup"
  linkedin = ""
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  featured_image = ""
  recent_posts_number = 2
