baseURL = "https://mallozup.github.io/"
languageCode = "en-us"
title = "Dario Maiocchi"
theme = "coder"

paginate = 20
canonifyurls = true

[params]
    author = "Dario Maiocchi"
    info = "Critical thinker, Senior software developer| Painter"
    description = "Dario Maiocchi's personal website"
    keywords = "foss, lisp, linux, clojure and other stuff around software"
    footercontent = "free software, free thoughts"

    rtl = false

    math = true
    custom_css = ["css/custom.css"]


# Social links
[[params.social]]
    name = "Github"
    icon = "fab fa-github fa-2x"
    weight = 1
    url = "https://github.com/MalloZup"
[[params.social]]
    name = "Twitter"
    icon = "fab fa-twitter fa-2x"
    weight = 3
    url = "https://twitter.com/DarioMaiocchi"

[[params.social]]
    name = "Instagram Paintings"
    icon = "fab fa-instagram fa-2x"
    weight = 2
    url = "https://www.instagram.com/dario_maiocchi_art/"

[[params.social]]
    name = "LinkedIn"
    icon = "fab fa-linkedin"
    weight = 4
    url = "https://www.linkedin.com/in/dario-maiocchi-1290b6155/"


# Menu links
[[menu.main]]
    name = "Technical Blog"
    weight = 1
    url  = "/posts/"
[[menu.main]]
    name = "Achivements"
    weight = 1
    url  = "/ac/"


